# Generated by Django 4.1.7 on 2023-04-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='real_estate',
            name='full_address',
        ),
        migrations.AlterField(
            model_name='real_estateimages',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.real_estate', verbose_name='Помещение '),
        ),
    ]
