# Generated by Django 4.1.7 on 2023-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_real_estate_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='first_photo',
            field=models.ImageField(blank=True, upload_to='real_estate_first/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
