# Generated by Django 4.1.7 on 2023-05-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_real_estate_first_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
