# Generated by Django 4.1.7 on 2023-05-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_real_estate_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='real_estate',
            options={'ordering': ['id'], 'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='real_estateimages',
            options={'ordering': ['real_estate'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='real_estateimages',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.real_estate', verbose_name='Помещение'),
        ),
    ]
